# Generated by Django 5.1.3 on 2025-01-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soups',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
