# Generated by Django 5.1.3 on 2025-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_alter_soups_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soups',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
