# Generated by Django 5.1.3 on 2025-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0003_alter_soups_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickAndEasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Starters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StirFry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VegBiryani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
            ],
        ),
    ]
