# Generated by Django 5.1.3 on 2025-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0005_alter_curries_name_alter_fastfood_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soups',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
