# Generated by Django 5.1.3 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juices',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='milkshakes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='smoothies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tea',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
