# Generated by Django 5.1.3 on 2025-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_alter_coffee_name_alter_juices_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='juices',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='milkshakes',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='smoothies',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
