# Generated by Django 5.1.3 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fruits',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nuts',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
