# Generated by Django 5.1.3 on 2025-02-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_alter_cakes_name_alter_chocolate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chocolate',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cookies',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nuts',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
