# Generated by Django 5.1.3 on 2025-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matter', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matter', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
