# Generated by Django 5.1.3 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chips',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fries',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='springrolls',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
