# Generated by Django 5.1.3 on 2025-02-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_chips_name_alter_fries_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chips',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fries',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='springrolls',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='traditional',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
