# Generated by Django 5.1.3 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapati',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dosa',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='idly',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parota',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puri',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vada',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
