# Generated by Django 5.1.3 on 2025-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffins', '0002_alter_chapati_name_alter_dosa_name_alter_idly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapati',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dosa',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='idly',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parota',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='puri',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vada',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
