# Generated by Django 5.1.3 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonveg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beef',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pork',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seafood',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='starters',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
