# Generated by Django 5.1.3 on 2025-02-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonveg', '0002_alter_beef_name_alter_chicken_name_alter_meat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beef',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chicken',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meat',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pork',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seafood',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='starters',
            name='video',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
